import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    home: 'Home',
    tours: 'Tours',
    halalTourism: 'Halal Tourism',
    destinations: 'Destinations',
    contact: 'Contact',
    login: 'Login',
    register: 'Sign Up',
    bookNow: 'Book Now',
    myDashboard: 'My Dashboard',
    logout: 'Logout',
    
    // Home Page
    heroTitle: 'Experience the Wild,',
    heroSubtitle: 'Without Compromising Your Faith',
    heroDescription: 'Premium African safaris with guaranteed Halal meals, private prayer facilities, and modest-friendly itineraries.',
    certified: '100% MUSLIM-FRIENDLY & HALAL CERTIFIED',
    exploreTours: 'Explore Tours',
    whyChooseUs: 'Why Choose Yalamlam?',
    
    // Common
    price: 'Price',
    duration: 'Duration',
    days: 'Days',
    learnMore: 'Learn More',
    viewDetails: 'View Details',
    startingFrom: 'Starting from',
    perPerson: 'per person',
    bookThisTour: 'Book This Tour Now',
    noPaymentRequired: 'No payment required today. We will contact you to confirm availability.',
    needHelp: 'Need help? WhatsApp us',
    freeCancellation: 'Free cancellation up to 48h before',
    
    // Tour Details
    aboutTour: 'About This Tour',
    itinerary: 'Day-by-Day Itinerary',
    included: "What's Included",
    excluded: "What's Excluded",
    halalCertified: '100% Halal Certified',
    customerReviews: 'Customer Reviews',
    writeReview: 'Write a Review',
    shareExperience: 'Share your experience',
    yourName: 'Your Name',
    rating: 'Rating',
    excellent: 'Excellent',
    good: 'Good',
    average: 'Average',
    poor: 'Poor',
    terrible: 'Terrible',
    tellUsAboutTrip: 'Tell us about your trip...',
    submitReview: 'Submit Review',
    noReviewsYet: 'No reviews yet. Be the first to share your experience!',
    reviewPending: 'JazakAllah Khair! Your review has been submitted and is pending admin approval.',
    
    // Booking
    bookingForm: 'Booking Form',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    startDate: 'Start Date',
    endDate: 'End Date',
    numberOfGuests: 'Number of Guests',
    specialRequests: 'Special Requests',
    submitBooking: 'Submit Booking Request',
    bookingSuccess: 'Booking request submitted successfully! We will contact you within 24 hours.',
    
    // Contact
    contactUs: 'Contact Us',
    contactDescription: 'Have questions? We\'re here to help you plan your perfect Halal safari.',
    name: 'Name',
    message: 'Message',
    sendMessage: 'Send Message',
    messageSuccess: 'Message sent successfully! We\'ll get back to you soon.',
    
    // Footer
    quickLinks: 'Quick Links',
    legalPolicies: 'Legal & Policies',
    termsConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    cancellationPolicy: 'Cancellation Policy',
    contactInfo: 'Contact Us',
    reservations: 'Reservations',
    zanzibarOffice: 'Zanzibar Office',
    customerSupport: 'Customer Support',
    allRightsReserved: 'All Rights Reserved',
    
    // Filters
    searchTours: 'Search tours or locations...',
    allCategories: 'All Categories',
    anyPrice: 'Any Price',
    under500: 'Under $500',
    under1000: 'Under $1,000',
    under2000: 'Under $2,000',
    under5000: 'Under $5,000',
    sortBy: 'Sort By',
    newestFirst: 'Newest First',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    durationShort: 'Duration: Shortest First',
    showingTours: 'Showing',
    toursPlural: 'tours',
    tour: 'tour',
    noToursFound: 'No tours found',
    tryAdjustingFilters: 'Try adjusting your filters or search query.',
    clearAllFilters: 'Clear all filters',
    
    // Categories
    zanzibarTours: 'Zanzibar Tours',
    tanzaniaSafaris: 'Tanzania Safaris',
    halalPackages: 'Halal Packages',
    kilimanjaro: 'Kilimanjaro',

    // Navbar
    selectLanguage: 'SELECT LANGUAGE',

    // Home - Why Choose Us cards
    halalMealsTitle: '100% Halal Meals',
    halalMealsDesc: 'Every meal is strictly Halal certified, prepared in clean, modest environments.',
    prayerFacilitiesTitle: 'Prayer Facilities',
    prayerFacilitiesDesc: 'Itineraries are built around prayer times with guaranteed access to clean mosques.',
    modestSafeTitle: 'Modest & Safe',
    modestSafeDesc: 'Private transfers, modest-friendly guides, and family-oriented environments.',

    // Tours page
    exploreToursTitle: 'Explore Our Tours',
    exploreToursSubtitle: 'Discover our carefully curated Halal-friendly safaris, Zanzibar beach getaways, and Kilimanjaro adventures.',
    loadingTours: 'Loading tours...',

    // Tour Details page
    backToAllTours: '← Back to All Tours',
    loadingTourDetails: 'Loading tour details...',
    tourNotFound: 'Tour not found.',
    goBack: 'Go back',
    whatsIncluded: "What's Included",
    whatsExcluded: "What's Excluded",
    outOf5: 'out of 5',
    reviewsWord: 'reviews',
    cancel: 'Cancel',
    submittingEllipsis: 'Submitting...',

    // Halal Tourism page
    yourFaithJourney: 'Your Faith, Your Journey',
    ultimateHalalExp: 'The Ultimate Halal Tourism Experience',
    ultimateHalalExpDesc: 'Explore the wild beauty of Tanzania and the paradise of Zanzibar without ever compromising your Islamic values. We handle the details; you enjoy the blessings.',
    whyTravelWithUs: 'Why Travel With Us?',
    whyTravelWithUsDesc: "We don't just add Halal food to a standard tour. We build the entire itinerary from the ground up with the Muslim traveler in mind.",
    pillarDiningTitle: '100% Halal Dining',
    pillarDiningDesc: 'We partner exclusively with certified Halal kitchens. From gourmet lodge dinners to packed safari lunches, you will never have to question your food. No alcohol in the minibar, no cross-contamination.',
    pillarPrayerTitle: 'Prayer Facilities Everywhere',
    pillarPrayerDesc: 'Every vehicle is equipped with a clean prayer mat and Qibla compass. Our partner lodges provide dedicated prayer rooms, and our guides are trained to adjust the itinerary around Salah times.',
    pillarTravelTitle: 'Private & Modest Travel',
    pillarTravelDesc: 'Travel in your own private 4x4 safari vehicle with just your family and your guide. We avoid crowded, mixed-gender group tours, ensuring your privacy and modesty are always respected.',
    pillarGuidesTitle: 'Female Guides & Staff',
    pillarGuidesDesc: 'Traveling with the ladies? We can arrange female tour guides, female drivers, and women-only spa and excursion activities for a completely comfortable experience.',
    pillarRamadanTitle: 'Ramadan & Eid Specials',
    pillarRamadanDesc: 'Traveling during the holy month? We provide customized Suhoor and Iftar schedules, packed iftar boxes for game drives, and special Eid celebration arrangements.',
    pillarEthicalTitle: 'Ethical & Responsible',
    pillarEthicalDesc: 'Islam teaches us to be stewards of the earth. Our safaris are eco-friendly, we respect local wildlife, and we give back to the local Tanzanian communities we visit.',
    readyWorryFree: 'Ready for a Worry-Free Safari?',
    readyWorryFreeDesc: 'Let us craft a custom itinerary that perfectly balances adventure, relaxation, and your spiritual needs.',
    planMyHalalTrip: 'Plan My Halal Trip',

    // Booking page
    planSafariTitle: 'Plan Your Halal Safari',
    planSafariDesc: 'Fill in your details below. We will customize everything to your faith and comfort.',
    step: 'Step',
    of: 'of',
    complete: 'Complete',
    step1Title: '1. Trip Details',
    whereToGo: 'Where do you want to go?',
    destZanzibar: 'Zanzibar (Beach & Stone Town)',
    destSerengeti: 'Serengeti & Ngorongoro Safari',
    destKilimanjaro: 'Kilimanjaro Trekking',
    destCustom: 'Custom Multi-Destination',
    step2Title: '2. Faith & Comfort Preferences',
    step2Subtitle: 'Select all that apply to ensure your trip aligns with your values.',
    halalMealsRequired: '100% Halal Meals Required',
    prayerFacilitiesQibla: 'Prayer Facilities & Qibla Direction in Rooms',
    privateVehicleLabel: 'Private 4x4 Vehicle (Family Only)',
    femaleGuideLabel: 'Female Tour Guide (for women-only or modesty preference)',
    modestActivitiesLabel: 'Modest-Friendly Activities Only (No mixed swimming, etc.)',
    step3Title: '3. Stay & Play',
    accommodationPref: 'Accommodation Preference',
    accLuxury: 'Luxury Safari Lodge / Resort',
    accVilla: 'Private Family Villa',
    accBudget: 'Budget-Friendly Camp',
    accHalalHotel: 'Certified Halal Hotel',
    activitiesInterest: 'Activities of Interest (Select multiple)',
    actWildlifeSafari: 'Wildlife Safari',
    actSnorkelling: 'Snorkelling',
    actSpiceTour: 'Spice Tour',
    actCulturalVillage: 'Cultural Village',
    actDolphinTour: 'Dolphin Tour',
    actSunsetCruise: 'Sunset Cruise',
    step4Title: '4. Contact Details',
    whatsappNumberLabel: 'WhatsApp Number (Include Country Code)',
    specialRequestsPlaceholder: 'e.g., Traveling in Ramadan, need a room near the mosque, celebrating honeymoon...',
    back: 'Back',
    nextStep: 'Next Step',
    savingRequest: 'Saving Request...',
    emailAddress: 'Email Address',

    // Contact page
    getInTouch: 'Get in Touch',
    getInTouchDesc: 'Have questions about our Halal tours? Want to customize an itinerary? We are here to help you plan your perfect trip.',
    callWhatsappUs: 'Call or WhatsApp Us',
    availableHours: 'Available 8:00 AM - 8:00 PM EAT',
    emailUsTitle: 'Email Us',
    replyWithin24: 'We reply within 24 hours',
    visitOurOffice: 'Visit Our Office',
    officeLocation: 'Stone Town, Zanzibar',
    officeCountry: 'Tanzania, East Africa',
    sendUsMessageTitle: 'Send us a Message',
    sendUsMessageDesc: "Fill out the form below and our team will get back to you shortly, Insha'Allah.",
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    yourMessage: 'Your Message',
    sendingEllipsis: 'Sending...',
    contactSuccessBanner: 'JazakAllah Khair! Your message has been sent successfully.',

    // Destinations page
    discoverTanzania: 'Discover Tanzania',
    discoverTanzaniaDesc: 'From the snow-capped peaks of Kilimanjaro to the turquoise waters of the Indian Ocean.',
    toursAvailable: 'Tours Available',
    viewToursLink: 'View Tours',
    dZanzibarName: 'Zanzibar Island',
    dZanzibarTagline: 'Spice Island & Beach Paradise',
    dZanzibarDesc: 'Relax on pristine white sands, explore the historic Stone Town, and enjoy world-class Halal seafood.',
    dSerengetiName: 'Serengeti National Park',
    dSerengetiTagline: 'The Great Migration',
    dSerengetiDesc: 'Witness millions of wildebeest and the Big Five in their natural, untamed habitat.',
    dNgorongoroName: 'Ngorongoro Crater',
    dNgorongoroTagline: 'The Garden of Eden',
    dNgorongoroDesc: "Descend into the world's largest intact volcanic caldera, teeming with wildlife year-round.",
    dKilimanjaroName: 'Mount Kilimanjaro',
    dKilimanjaroTagline: 'Roof of Africa',
    dKilimanjaroDesc: 'Challenge yourself with a guided trek to the highest peak in Africa, with Halal mountain cuisine.',
    dTarangireName: 'Tarangire National Park',
    dTarangireTagline: 'Land of Giants',
    dTarangireDesc: 'Famous for its massive elephant herds and ancient baobab trees. A peaceful, less-crowded safari.',
    dManyaraName: 'Lake Manyara',
    dManyaraTagline: 'Tree Lions & Flamingos',
    dManyaraDesc: 'A stunning groundwater forest home to tree-climbing lions and massive flocks of pink flamingos.',

    // Login / Register / Dashboard
    loginSubtitle: 'Yalamlam Travel & Tours',
    password: 'Password',
    invalidCredentials: 'Invalid email or password. Please try again.',
    loggingIn: 'Logging in...',
    noAccount: "Don't have an account?",
    signUpHere: 'Sign up here',
    staffHint: 'Staff: Use your company email to access the admin panel',
    createAccount: 'Create an Account',
    joinYalamlam: 'Join Yalamlam Travel for exclusive deals',
    creatingAccount: 'Creating Account...',
    signUp: 'Sign Up',
    alreadyHaveAccount: 'Already have an account?',
    logInHere: 'Log in here',
    registerSuccess: '✅ Account created successfully! You can now log in.',
    welcomeBack: 'Welcome back,',
    myBookings: 'My Bookings',
    noBookingsYet: "You haven't made any bookings yet.",
    browseTours: 'Browse Tours',
    refLabel: 'Ref:',
    datesLabel: 'Dates:',
    guestsLabel: 'Guests:',

    // Email OTP login & Forgot/Reset password
    loginWithPassword: 'Password',
    loginWithEmailCode: 'Email Code',
    sendCode: 'Send Code',
    sendingCode: 'Sending...',
    codeSentTo: 'We sent a 6-digit code to',
    enterCode: 'Enter the 6-digit code',
    verifyAndLogin: 'Verify & Log In',
    verifyingCode: 'Verifying...',
    resendCode: 'Resend code',
    resendCodeIn: 'Resend in',
    invalidCode: 'Invalid or expired code. Please try again.',
    didntGetCode: "Didn't get the code?",
    useDifferentEmail: 'Use a different email',
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordSubtitle: "Enter your email and we'll send you a reset link",
    sendResetLink: 'Send Reset Link',
    sendingResetLink: 'Sending...',
    resetLinkSentTitle: 'Check Your Email',
    resetLinkSentMessage: "If an account exists for that email, we've sent a password reset link. It may take a minute to arrive.",
    backToLogin: 'Back to Login',
    resetPasswordTitle: 'Reset Your Password',
    resetPasswordSubtitle: 'Choose a new password for your account',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    resetPasswordButton: 'Reset Password',
    resettingPassword: 'Resetting...',
    passwordsDontMatch: 'Passwords do not match.',
    passwordTooShort: 'Password must be at least 6 characters.',
    resetPasswordSuccess: '✅ Password updated successfully! Redirecting to login...',
    invalidResetLink: 'This password reset link is invalid or has expired.',
    requestNewResetLink: 'Request a new one',
    changePasswordTitle: 'Change Password',
    changePasswordSubtitle: 'Update the password for your account',
    currentPassword: 'Current Password',
    changePasswordButton: 'Change Password',
    changingPassword: 'Updating...',
    passwordChangedSuccess: '✅ Password changed successfully.',
    incorrectCurrentPassword: 'Current password is incorrect.',
  },

  ar: {
    // Navigation
    home: 'الرئيسية',
    tours: 'الجولات',
    halalTourism: 'السياحة الحلال',
    destinations: 'الوجهات',
    contact: 'اتصل بنا',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    bookNow: 'احجز الآن',
    myDashboard: 'لوحة التحكم',
    logout: 'تسجيل الخروج',
    
    // Home Page
    heroTitle: 'استكشف البرية،',
    heroSubtitle: 'دون المساس بإيمانك',
    heroDescription: 'رحلات سفاري أفريقية متميزة مع وجبات حلال مضمونة، ومرافق صلاة خاصة، وبرامج مناسبة للحياء.',
    certified: '100% صديق للمسلمين ومعتمد حلال',
    exploreTours: 'استكشف الجولات',
    whyChooseUs: 'لماذا تختار يلملم؟',
    
    // Common
    price: 'السعر',
    duration: 'المدة',
    days: 'أيام',
    learnMore: 'اعرف المزيد',
    viewDetails: 'عرض التفاصيل',
    startingFrom: 'ابتداءً من',
    perPerson: 'للشخص',
    bookThisTour: 'احجز هذه الجولة الآن',
    noPaymentRequired: 'لا حاجة للدفع اليوم. سنتواصل معك لتأكيد التوفر.',
    needHelp: 'تحتاج مساعدة؟ راسلنا على واتساب',
    freeCancellation: 'إلغاء مجاني حتى 48 ساعة قبل',
    
    // Tour Details
    aboutTour: 'عن هذه الجولة',
    itinerary: 'البرنامج اليومي',
    included: 'ما يشمل',
    excluded: 'ما لا يشمل',
    halalCertified: 'معتمد 100% حلال',
    customerReviews: 'تقييمات العملاء',
    writeReview: 'اكتب تقييمك',
    shareExperience: 'شارك تجربتك',
    yourName: 'اسمك',
    rating: 'التقييم',
    excellent: 'ممتاز',
    good: 'جيد',
    average: 'متوسط',
    poor: 'ضعيف',
    terrible: 'سيء جداً',
    tellUsAboutTrip: 'أخبرنا عن رحلتك...',
    submitReview: 'إرسال التقييم',
    noReviewsYet: 'لا توجد تقييمات بعد. كن الأول!',
    reviewPending: 'جزاك الله خيراً! تم إرسال تقييمك في انتظار الموافقة.',
    
    // Booking
    bookingForm: 'نموذج الحجز',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    startDate: 'تاريخ البدء',
    endDate: 'تاريخ الانتهاء',
    numberOfGuests: 'عدد الضيوف',
    specialRequests: 'طلبات خاصة',
    submitBooking: 'إرسال طلب الحجز',
    bookingSuccess: 'تم إرسال طلب الحجز بنجاح! سنتواصل معك خلال 24 ساعة.',
    
    // Contact
    contactUs: 'اتصل بنا',
    contactDescription: 'هل لديك أسئلة؟ نحن هنا لمساعدتك في التخطيط لرحلتك المثالية.',
    name: 'الاسم',
    message: 'الرسالة',
    sendMessage: 'إرسال الرسالة',
    messageSuccess: 'تم إرسال الرسالة بنجاح! سنتواصل معك قريباً.',
    
    // Footer
    quickLinks: 'روابط سريعة',
    legalPolicies: 'الشروط والسياسات',
    termsConditions: 'الشروط والأحكام',
    privacyPolicy: 'سياسة الخصوصية',
    cancellationPolicy: 'سياسة الإلغاء',
    contactInfo: 'اتصل بنا',
    reservations: 'الحجوزات',
    zanzibarOffice: 'مكتب زنجبار',
    customerSupport: 'دعم العملاء',
    allRightsReserved: 'جميع الحقوق محفوظة',
    
    // Filters
    searchTours: 'ابحث عن الجولات أو الوجهات...',
    allCategories: 'جميع الفئات',
    anyPrice: 'أي سعر',
    under500: 'أقل من 500$',
    under1000: 'أقل من 1,000$',
    under2000: 'أقل من 2,000$',
    under5000: 'أقل من 5,000$',
    sortBy: 'ترتيب حسب',
    newestFirst: 'الأحدث أولاً',
    priceLowHigh: 'السعر: من الأقل للأعلى',
    priceHighLow: 'السعر: من الأعلى للأقل',
    durationShort: 'المدة: الأقصر أولاً',
    showingTours: 'عرض',
    toursPlural: 'جولة',
    tour: 'جولة',
    noToursFound: 'لم يتم العثور على جولات',
    tryAdjustingFilters: 'حاول تعديل الفلاتر أو البحث.',
    clearAllFilters: 'مسح جميع الفلاتر',
    
    // Categories
    zanzibarTours: 'جولات زنجبار',
    tanzaniaSafaris: 'سفاري تنزانيا',
    halalPackages: 'باقات حلال',
    kilimanjaro: 'كليمنجارو',

    // Navbar
    selectLanguage: 'اختر اللغة',

    // Home - Why Choose Us cards
    halalMealsTitle: '100% وجبات حلال',
    halalMealsDesc: 'كل وجبة معتمدة حلال بشكل صارم، وتُحضَّر في بيئة نظيفة ومحتشمة.',
    prayerFacilitiesTitle: 'مرافق الصلاة',
    prayerFacilitiesDesc: 'يتم تصميم البرامج حول أوقات الصلاة مع ضمان الوصول إلى مساجد نظيفة.',
    modestSafeTitle: 'محتشم وآمن',
    modestSafeDesc: 'تنقلات خاصة، ومرشدون يراعون الحياء، وأجواء عائلية.',

    // Tours page
    exploreToursTitle: 'استكشف جولاتنا',
    exploreToursSubtitle: 'اكتشف رحلات السفاري الحلال المختارة بعناية، وعطلات شاطئ زنجبار، ومغامرات كليمنجارو.',
    loadingTours: 'جاري تحميل الجولات...',

    // Tour Details page
    backToAllTours: '← العودة إلى جميع الجولات',
    loadingTourDetails: 'جاري تحميل تفاصيل الجولة...',
    tourNotFound: 'لم يتم العثور على الجولة.',
    goBack: 'العودة',
    whatsIncluded: 'ما يشمل',
    whatsExcluded: 'ما لا يشمل',
    outOf5: 'من 5',
    reviewsWord: 'تقييمات',
    cancel: 'إلغاء',
    submittingEllipsis: 'جاري الإرسال...',

    // Halal Tourism page
    yourFaithJourney: 'إيمانك، رحلتك',
    ultimateHalalExp: 'تجربة السياحة الحلال المثالية',
    ultimateHalalExpDesc: 'استكشف جمال تنزانيا البري وجنة زنجبار دون المساس بقيمك الإسلامية أبداً. نحن نهتم بالتفاصيل؛ وأنت تستمتع بالبركات.',
    whyTravelWithUs: 'لماذا تسافر معنا؟',
    whyTravelWithUsDesc: 'نحن لا نضيف الطعام الحلال فقط إلى جولة عادية. نحن نبني البرنامج بالكامل من الأساس مع مراعاة المسافر المسلم.',
    pillarDiningTitle: 'مطاعم حلال 100%',
    pillarDiningDesc: 'نتعاون حصرياً مع مطابخ حلال معتمدة. من عشاء النُّزل الفاخر إلى وجبات السفاري المعبأة، لن تضطر أبداً للتساؤل عن طعامك. لا كحول في الميني بار، ولا تلوث متبادل.',
    pillarPrayerTitle: 'مرافق صلاة في كل مكان',
    pillarPrayerDesc: 'كل مركبة مجهزة بسجادة صلاة نظيفة وبوصلة قبلة. تقدم النُّزل الشريكة غرف صلاة مخصصة، ومرشدونا مدربون على تعديل البرنامج حسب أوقات الصلاة.',
    pillarTravelTitle: 'سفر خاص ومحتشم',
    pillarTravelDesc: 'سافر في مركبة سفاري خاصة 4x4 مع عائلتك ومرشدك فقط. نتجنب الجولات الجماعية المزدحمة والمختلطة، لضمان خصوصيتك واحتشامك دائماً.',
    pillarGuidesTitle: 'مرشدات وطاقم نسائي',
    pillarGuidesDesc: 'تسافرين مع السيدات؟ يمكننا ترتيب مرشدات سياحيات، وسائقات، وأنشطة سبا ورحلات خاصة بالنساء فقط لتجربة مريحة تماماً.',
    pillarRamadanTitle: 'عروض رمضان والعيد',
    pillarRamadanDesc: 'تسافر خلال الشهر الفضيل؟ نوفر جداول سحور وإفطار مخصصة، وصناديق إفطار جاهزة لرحلات السفاري، وترتيبات خاصة للاحتفال بالعيد.',
    pillarEthicalTitle: 'أخلاقي ومسؤول',
    pillarEthicalDesc: 'يعلمنا الإسلام أن نكون أمناء على الأرض. رحلات السفاري لدينا صديقة للبيئة، ونحترم الحياة البرية المحلية، ونرد الجميل للمجتمعات التنزانية التي نزورها.',
    readyWorryFree: 'مستعد لسفاري بلا هموم؟',
    readyWorryFreeDesc: 'دعنا نصمم برنامجاً مخصصاً يوازن تماماً بين المغامرة والاسترخاء واحتياجاتك الروحية.',
    planMyHalalTrip: 'خطط لرحلتي الحلال',

    // Booking page
    planSafariTitle: 'خطط لسفاريك الحلال',
    planSafariDesc: 'املأ بياناتك أدناه. سنخصص كل شيء ليتناسب مع إيمانك وراحتك.',
    step: 'خطوة',
    of: 'من',
    complete: 'مكتمل',
    step1Title: '1. تفاصيل الرحلة',
    whereToGo: 'إلى أين تريد الذهاب؟',
    destZanzibar: 'زنجبار (الشاطئ وستون تاون)',
    destSerengeti: 'سفاري السيرينجيتي ونجورونجورو',
    destKilimanjaro: 'تسلق كليمنجارو',
    destCustom: 'وجهات متعددة مخصصة',
    step2Title: '2. تفضيلات الإيمان والراحة',
    step2Subtitle: 'حدد كل ما ينطبق لضمان توافق رحلتك مع قيمك.',
    halalMealsRequired: 'وجبات حلال 100% مطلوبة',
    prayerFacilitiesQibla: 'مرافق صلاة واتجاه القبلة في الغرف',
    privateVehicleLabel: 'مركبة خاصة 4x4 (للعائلة فقط)',
    femaleGuideLabel: 'مرشدة سياحية (لتفضيل النساء فقط أو الاحتشام)',
    modestActivitiesLabel: 'أنشطة محتشمة فقط (بدون سباحة مختلطة، إلخ)',
    step3Title: '3. الإقامة والأنشطة',
    accommodationPref: 'تفضيل الإقامة',
    accLuxury: 'نُزل/منتجع سفاري فاخر',
    accVilla: 'فيلا عائلية خاصة',
    accBudget: 'مخيم اقتصادي',
    accHalalHotel: 'فندق حلال معتمد',
    activitiesInterest: 'الأنشطة المفضلة (اختر أكثر من واحد)',
    actWildlifeSafari: 'سفاري الحياة البرية',
    actSnorkelling: 'الغطس',
    actSpiceTour: 'جولة التوابل',
    actCulturalVillage: 'قرية ثقافية',
    actDolphinTour: 'جولة الدلافين',
    actSunsetCruise: 'رحلة غروب الشمس',
    step4Title: '4. تفاصيل الاتصال',
    whatsappNumberLabel: 'رقم واتساب (مع رمز الدولة)',
    specialRequestsPlaceholder: 'مثال: السفر في رمضان، الحاجة لغرفة قرب المسجد، الاحتفال بشهر العسل...',
    back: 'رجوع',
    nextStep: 'الخطوة التالية',
    savingRequest: 'جاري الحفظ...',
    emailAddress: 'البريد الإلكتروني',

    // Contact page
    getInTouch: 'تواصل معنا',
    getInTouchDesc: 'هل لديك أسئلة حول جولاتنا الحلال؟ تريد تخصيص برنامج رحلة؟ نحن هنا لمساعدتك في التخطيط لرحلتك المثالية.',
    callWhatsappUs: 'اتصل بنا أو راسلنا على واتساب',
    availableHours: 'متاحون من 8:00 صباحاً حتى 8:00 مساءً بتوقيت شرق أفريقيا',
    emailUsTitle: 'راسلنا بالبريد الإلكتروني',
    replyWithin24: 'نرد خلال 24 ساعة',
    visitOurOffice: 'زر مكتبنا',
    officeLocation: 'ستون تاون، زنجبار',
    officeCountry: 'تنزانيا، شرق أفريقيا',
    sendUsMessageTitle: 'أرسل لنا رسالة',
    sendUsMessageDesc: 'املأ النموذج أدناه وسيتواصل معك فريقنا قريباً إن شاء الله.',
    fullName: 'الاسم الكامل',
    phoneNumber: 'رقم الهاتف',
    yourMessage: 'رسالتك',
    sendingEllipsis: 'جاري الإرسال...',
    contactSuccessBanner: 'جزاك الله خيراً! تم إرسال رسالتك بنجاح.',

    // Destinations page
    discoverTanzania: 'اكتشف تنزانيا',
    discoverTanzaniaDesc: 'من قمم كليمنجارو المغطاة بالثلوج إلى مياه المحيط الهندي الفيروزية.',
    toursAvailable: 'جولة متاحة',
    viewToursLink: 'عرض الجولات',
    dZanzibarName: 'جزيرة زنجبار',
    dZanzibarTagline: 'جزيرة التوابل وجنة الشاطئ',
    dZanzibarDesc: 'استرخِ على الرمال البيضاء النقية، واستكشف ستون تاون التاريخية، واستمتع بمأكولات بحرية حلال عالمية المستوى.',
    dSerengetiName: 'حديقة السيرينجيتي الوطنية',
    dSerengetiTagline: 'الهجرة الكبرى',
    dSerengetiDesc: 'شاهد ملايين حيوانات الجنو والخمسة الكبار في موطنها الطبيعي البري.',
    dNgorongoroName: 'فوهة نجورونجورو',
    dNgorongoroTagline: 'حديقة عدن',
    dNgorongoroDesc: 'انزل إلى أكبر فوهة بركانية سليمة في العالم، الزاخرة بالحياة البرية على مدار العام.',
    dKilimanjaroName: 'جبل كليمنجارو',
    dKilimanjaroTagline: 'سقف أفريقيا',
    dKilimanjaroDesc: 'تحدَّ نفسك برحلة تسلق موجهة إلى أعلى قمة في أفريقيا، مع مأكولات جبلية حلال.',
    dTarangireName: 'حديقة تارانجيري الوطنية',
    dTarangireTagline: 'أرض العمالقة',
    dTarangireDesc: 'مشهورة بقطعان الفيلة الضخمة وأشجار الباوباب القديمة. سفاري هادئة وأقل ازدحاماً.',
    dManyaraName: 'بحيرة مانيارا',
    dManyaraTagline: 'أسود الأشجار والفلامنغو',
    dManyaraDesc: 'غابة جوفية مذهلة موطن لأسود متسلقة الأشجار وأسراب ضخمة من طيور الفلامنغو الوردية.',

    // Login / Register / Dashboard
    loginSubtitle: 'يلملم للسفر والسياحة',
    password: 'كلمة المرور',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة. حاول مرة أخرى.',
    loggingIn: 'جاري تسجيل الدخول...',
    noAccount: 'ليس لديك حساب؟',
    signUpHere: 'أنشئ حساباً من هنا',
    staffHint: 'الموظفون: استخدم بريدك الإلكتروني الرسمي للوصول إلى لوحة الإدارة',
    createAccount: 'إنشاء حساب',
    joinYalamlam: 'انضم إلى يلملم للسفر للحصول على عروض حصرية',
    creatingAccount: 'جاري إنشاء الحساب...',
    signUp: 'إنشاء حساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    logInHere: 'سجل الدخول من هنا',
    registerSuccess: '✅ تم إنشاء الحساب بنجاح! يمكنك الآن تسجيل الدخول.',
    welcomeBack: 'مرحباً بعودتك،',
    myBookings: 'حجوزاتي',
    noBookingsYet: 'لم تقم بأي حجز بعد.',
    browseTours: 'تصفح الجولات',
    refLabel: 'المرجع:',
    datesLabel: 'التواريخ:',
    guestsLabel: 'الضيوف:',

    // Email OTP login & Forgot/Reset password
    loginWithPassword: 'كلمة المرور',
    loginWithEmailCode: 'رمز عبر البريد الإلكتروني',
    sendCode: 'إرسال الرمز',
    sendingCode: 'جارٍ الإرسال...',
    codeSentTo: 'أرسلنا رمزاً مكوناً من 6 أرقام إلى',
    enterCode: 'أدخل الرمز المكون من 6 أرقام',
    verifyAndLogin: 'تحقق وسجّل الدخول',
    verifyingCode: 'جارٍ التحقق...',
    resendCode: 'إعادة إرسال الرمز',
    resendCodeIn: 'إعادة الإرسال خلال',
    invalidCode: 'الرمز غير صحيح أو منتهي الصلاحية. حاول مرة أخرى.',
    didntGetCode: 'لم تستلم الرمز؟',
    useDifferentEmail: 'استخدم بريداً إلكترونياً آخر',
    forgotPassword: 'نسيت كلمة المرور؟',
    forgotPasswordTitle: 'نسيت كلمة المرور',
    forgotPasswordSubtitle: 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين',
    sendResetLink: 'إرسال رابط إعادة التعيين',
    sendingResetLink: 'جارٍ الإرسال...',
    resetLinkSentTitle: 'تحقق من بريدك الإلكتروني',
    resetLinkSentMessage: 'إذا كان هناك حساب مرتبط بهذا البريد الإلكتروني، فقد أرسلنا رابط إعادة تعيين كلمة المرور. قد يستغرق وصوله دقيقة.',
    backToLogin: 'العودة لتسجيل الدخول',
    resetPasswordTitle: 'إعادة تعيين كلمة المرور',
    resetPasswordSubtitle: 'اختر كلمة مرور جديدة لحسابك',
    newPassword: 'كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    resetPasswordButton: 'إعادة تعيين كلمة المرور',
    resettingPassword: 'جارٍ إعادة التعيين...',
    passwordsDontMatch: 'كلمتا المرور غير متطابقتين.',
    passwordTooShort: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
    resetPasswordSuccess: '✅ تم تحديث كلمة المرور بنجاح! جارٍ التحويل إلى تسجيل الدخول...',
    invalidResetLink: 'رابط إعادة تعيين كلمة المرور غير صالح أو منتهي الصلاحية.',
    requestNewResetLink: 'اطلب رابطاً جديداً',
    changePasswordTitle: 'تغيير كلمة المرور',
    changePasswordSubtitle: 'قم بتحديث كلمة المرور لحسابك',
    currentPassword: 'كلمة المرور الحالية',
    changePasswordButton: 'تغيير كلمة المرور',
    changingPassword: 'جارٍ التحديث...',
    passwordChangedSuccess: '✅ تم تغيير كلمة المرور بنجاح.',
    incorrectCurrentPassword: 'كلمة المرور الحالية غير صحيحة.',
  },

  fr: {
    // Navigation
    home: 'Accueil',
    tours: 'Circuits',
    halalTourism: 'Tourisme Halal',
    destinations: 'Destinations',
    contact: 'Contact',
    login: 'Connexion',
    register: 'S\'inscrire',
    bookNow: 'Réserver',
    myDashboard: 'Mon Tableau de Bord',
    logout: 'Déconnexion',
    
    // Home Page
    heroTitle: 'Découvrez la Nature,',
    heroSubtitle: 'Sans Compromettre Votre Foi',
    heroDescription: 'Safaris africains premium avec repas halal garantis, installations de prière privées et itinéraires adaptés.',
    certified: '100% COMPATIBLE MUSULMAN & CERTIFIÉ HALAL',
    exploreTours: 'Explorer les Circuits',
    whyChooseUs: 'Pourquoi Choisir Yalamlam?',
    
    // Common
    price: 'Prix',
    duration: 'Durée',
    days: 'Jours',
    learnMore: 'En Savoir Plus',
    viewDetails: 'Voir Détails',
    startingFrom: 'À partir de',
    perPerson: 'par personne',
    bookThisTour: 'Réserver ce Circuit',
    noPaymentRequired: 'Aucun paiement requis aujourd\'hui. Nous vous contacterons.',
    needHelp: 'Besoin d\'aide? WhatsApp-nous',
    freeCancellation: 'Annulation gratuite jusqu\'à 48h avant',
    
    // Tour Details
    aboutTour: 'À Propos de ce Circuit',
    itinerary: 'Itinéraire Jour par Jour',
    included: 'Ce qui est Inclus',
    excluded: 'Ce qui est Exclu',
    halalCertified: '100% Certifié Halal',
    customerReviews: 'Avis des Clients',
    writeReview: 'Écrire un Avis',
    shareExperience: 'Partagez votre expérience',
    yourName: 'Votre Nom',
    rating: 'Note',
    excellent: 'Excellent',
    good: 'Bien',
    average: 'Moyen',
    poor: 'Médiocre',
    terrible: 'Terrible',
    tellUsAboutTrip: 'Parlez-nous de votre voyage...',
    submitReview: 'Soumettre l\'Avis',
    noReviewsYet: 'Pas encore d\'avis. Soyez le premier!',
    reviewPending: 'JazakAllah Khair! Votre avis est en attente d\'approbation.',
    
    // Booking
    bookingForm: 'Formulaire de Réservation',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    startDate: 'Date de Début',
    endDate: 'Date de Fin',
    numberOfGuests: 'Nombre de Personnes',
    specialRequests: 'Demandes Spéciales',
    submitBooking: 'Soumettre la Réservation',
    bookingSuccess: 'Réservation soumise! Nous vous contacterons sous 24h.',
    
    // Contact
    contactUs: 'Contactez-nous',
    contactDescription: 'Des questions? Nous sommes là pour vous aider.',
    name: 'Nom',
    message: 'Message',
    sendMessage: 'Envoyer',
    messageSuccess: 'Message envoyé! Nous vous répondrons bientôt.',
    
    // Footer
    quickLinks: 'Liens Rapides',
    legalPolicies: 'Légal & Politiques',
    termsConditions: 'Conditions Générales',
    privacyPolicy: 'Politique de Confidentialité',
    cancellationPolicy: 'Politique d\'Annulation',
    contactInfo: 'Contactez-nous',
    reservations: 'Réservations',
    zanzibarOffice: 'Bureau Zanzibar',
    customerSupport: 'Support Client',
    allRightsReserved: 'Tous Droits Réservés',
    
    // Filters
    searchTours: 'Rechercher circuits ou destinations...',
    allCategories: 'Toutes Catégories',
    anyPrice: 'Tout Prix',
    under500: 'Moins de 500$',
    under1000: 'Moins de 1,000$',
    under2000: 'Moins de 2,000$',
    under5000: 'Moins de 5,000$',
    sortBy: 'Trier par',
    newestFirst: 'Plus Récents',
    priceLowHigh: 'Prix: Croissant',
    priceHighLow: 'Prix: Décroissant',
    durationShort: 'Durée: Plus Court',
    showingTours: 'Affichage',
    toursPlural: 'circuits',
    tour: 'circuit',
    noToursFound: 'Aucun circuit trouvé',
    tryAdjustingFilters: 'Essayez d\'ajuster vos filtres.',
    clearAllFilters: 'Effacer les filtres',
    
    // Categories
    zanzibarTours: 'Circuits Zanzibar',
    tanzaniaSafaris: 'Safaris Tanzanie',
    halalPackages: 'Forfaits Halal',
    kilimanjaro: 'Kilimandjaro',

    // Navbar
    selectLanguage: 'CHOISIR LA LANGUE',

    // Home - Why Choose Us cards
    halalMealsTitle: 'Repas 100% Halal',
    halalMealsDesc: 'Chaque repas est strictement certifié Halal, préparé dans un environnement propre et pudique.',
    prayerFacilitiesTitle: 'Installations de Prière',
    prayerFacilitiesDesc: 'Les itinéraires sont conçus autour des heures de prière avec un accès garanti à des mosquées propres.',
    modestSafeTitle: 'Pudique et Sûr',
    modestSafeDesc: 'Transferts privés, guides respectueux de la pudeur et environnements familiaux.',

    // Tours page
    exploreToursTitle: 'Explorez Nos Circuits',
    exploreToursSubtitle: 'Découvrez nos safaris halal soigneusement sélectionnés, nos escapades sur les plages de Zanzibar et nos aventures au Kilimandjaro.',
    loadingTours: 'Chargement des circuits...',

    // Tour Details page
    backToAllTours: '← Retour à Tous les Circuits',
    loadingTourDetails: 'Chargement des détails du circuit...',
    tourNotFound: 'Circuit introuvable.',
    goBack: 'Retour',
    whatsIncluded: 'Ce qui est Inclus',
    whatsExcluded: 'Ce qui est Exclu',
    outOf5: 'sur 5',
    reviewsWord: 'avis',
    cancel: 'Annuler',
    submittingEllipsis: 'Envoi en cours...',

    // Halal Tourism page
    yourFaithJourney: 'Votre Foi, Votre Voyage',
    ultimateHalalExp: "L'Expérience de Tourisme Halal Ultime",
    ultimateHalalExpDesc: "Explorez la beauté sauvage de la Tanzanie et le paradis de Zanzibar sans jamais compromettre vos valeurs islamiques. Nous gérons les détails ; vous profitez des bénédictions.",
    whyTravelWithUs: 'Pourquoi Voyager Avec Nous?',
    whyTravelWithUsDesc: "Nous n'ajoutons pas seulement de la nourriture Halal à un circuit standard. Nous construisons tout l'itinéraire en pensant au voyageur musulman.",
    pillarDiningTitle: 'Restauration 100% Halal',
    pillarDiningDesc: "Nous collaborons exclusivement avec des cuisines certifiées Halal. Des dîners gastronomiques au lodge aux déjeuners de safari emballés, vous n'aurez jamais à douter de votre nourriture. Pas d'alcool au minibar, pas de contamination croisée.",
    pillarPrayerTitle: 'Installations de Prière Partout',
    pillarPrayerDesc: "Chaque véhicule est équipé d'un tapis de prière propre et d'une boussole Qibla. Nos lodges partenaires offrent des salles de prière dédiées, et nos guides sont formés pour ajuster l'itinéraire selon les heures de Salah.",
    pillarTravelTitle: 'Voyage Privé et Pudique',
    pillarTravelDesc: "Voyagez dans votre propre véhicule de safari privé 4x4 avec seulement votre famille et votre guide. Nous évitons les circuits de groupe mixtes et bondés, garantissant toujours votre intimité et votre pudeur.",
    pillarGuidesTitle: 'Guides et Personnel Féminins',
    pillarGuidesDesc: "Vous voyagez entre femmes? Nous pouvons organiser des guides touristiques, des chauffeuses et des activités spa et excursions réservées aux femmes pour une expérience totalement confortable.",
    pillarRamadanTitle: 'Offres Ramadan et Aïd',
    pillarRamadanDesc: "Vous voyagez pendant le mois sacré? Nous proposons des horaires de Suhoor et Iftar personnalisés, des boîtes d'Iftar pour les safaris, et des arrangements spéciaux pour célébrer l'Aïd.",
    pillarEthicalTitle: 'Éthique et Responsable',
    pillarEthicalDesc: "L'Islam nous enseigne à être les gardiens de la terre. Nos safaris sont écologiques, nous respectons la faune locale et nous redonnons aux communautés tanzaniennes que nous visitons.",
    readyWorryFree: 'Prêt pour un Safari Sans Souci?',
    readyWorryFreeDesc: 'Laissez-nous concevoir un itinéraire sur mesure qui équilibre parfaitement aventure, détente et besoins spirituels.',
    planMyHalalTrip: 'Planifier Mon Voyage Halal',

    // Booking page
    planSafariTitle: 'Planifiez Votre Safari Halal',
    planSafariDesc: 'Remplissez vos informations ci-dessous. Nous personnaliserons tout selon votre foi et votre confort.',
    step: 'Étape',
    of: 'sur',
    complete: 'Complété',
    step1Title: '1. Détails du Voyage',
    whereToGo: 'Où voulez-vous aller?',
    destZanzibar: 'Zanzibar (Plage et Stone Town)',
    destSerengeti: 'Safari Serengeti et Ngorongoro',
    destKilimanjaro: 'Trek du Kilimandjaro',
    destCustom: 'Multi-Destination Personnalisée',
    step2Title: '2. Préférences de Foi et Confort',
    step2Subtitle: "Sélectionnez tout ce qui s'applique pour que votre voyage corresponde à vos valeurs.",
    halalMealsRequired: 'Repas 100% Halal Requis',
    prayerFacilitiesQibla: 'Installations de Prière et Direction Qibla dans les Chambres',
    privateVehicleLabel: 'Véhicule Privé 4x4 (Famille Uniquement)',
    femaleGuideLabel: 'Guide Touristique Féminine (préférence non-mixte ou pudique)',
    modestActivitiesLabel: 'Activités Pudiques Uniquement (Pas de baignade mixte, etc.)',
    step3Title: '3. Séjour et Activités',
    accommodationPref: "Préférence d'Hébergement",
    accLuxury: 'Lodge / Resort de Safari de Luxe',
    accVilla: 'Villa Familiale Privée',
    accBudget: 'Camp Économique',
    accHalalHotel: 'Hôtel Certifié Halal',
    activitiesInterest: "Activités d'Intérêt (Sélection multiple)",
    actWildlifeSafari: 'Safari Faune',
    actSnorkelling: 'Plongée avec Tuba',
    actSpiceTour: 'Circuit des Épices',
    actCulturalVillage: 'Village Culturel',
    actDolphinTour: 'Excursion aux Dauphins',
    actSunsetCruise: 'Croisière au Coucher du Soleil',
    step4Title: '4. Coordonnées',
    whatsappNumberLabel: 'Numéro WhatsApp (avec indicatif du pays)',
    specialRequestsPlaceholder: "ex: Voyage pendant le Ramadan, besoin d'une chambre près de la mosquée, célébration de lune de miel...",
    back: 'Retour',
    nextStep: 'Étape Suivante',
    savingRequest: 'Enregistrement en cours...',
    emailAddress: 'Adresse Email',

    // Contact page
    getInTouch: 'Contactez-Nous',
    getInTouchDesc: "Des questions sur nos circuits Halal? Envie de personnaliser un itinéraire? Nous sommes là pour vous aider à planifier votre voyage parfait.",
    callWhatsappUs: 'Appelez ou WhatsApp',
    availableHours: 'Disponible de 8h00 à 20h00 EAT',
    emailUsTitle: 'Envoyez-nous un Email',
    replyWithin24: 'Nous répondons sous 24 heures',
    visitOurOffice: 'Visitez Notre Bureau',
    officeLocation: 'Stone Town, Zanzibar',
    officeCountry: "Tanzanie, Afrique de l'Est",
    sendUsMessageTitle: 'Envoyez-nous un Message',
    sendUsMessageDesc: "Remplissez le formulaire ci-dessous et notre équipe vous répondra rapidement, Insha'Allah.",
    fullName: 'Nom Complet',
    phoneNumber: 'Numéro de Téléphone',
    yourMessage: 'Votre Message',
    sendingEllipsis: 'Envoi en cours...',
    contactSuccessBanner: 'JazakAllah Khair! Votre message a été envoyé avec succès.',

    // Destinations page
    discoverTanzania: 'Découvrez la Tanzanie',
    discoverTanzaniaDesc: "Des sommets enneigés du Kilimandjaro aux eaux turquoise de l'océan Indien.",
    toursAvailable: 'Circuits Disponibles',
    viewToursLink: 'Voir les Circuits',
    dZanzibarName: 'Île de Zanzibar',
    dZanzibarTagline: 'Île aux Épices et Paradis Balnéaire',
    dZanzibarDesc: 'Détendez-vous sur des sables blancs immaculés, explorez la Stone Town historique et savourez des fruits de mer Halal de classe mondiale.',
    dSerengetiName: 'Parc National du Serengeti',
    dSerengetiTagline: 'La Grande Migration',
    dSerengetiDesc: "Assistez à la migration de millions de gnous et observez les Big Five dans leur habitat naturel et sauvage.",
    dNgorongoroName: 'Cratère du Ngorongoro',
    dNgorongoroTagline: "Le Jardin d'Eden",
    dNgorongoroDesc: "Descendez dans la plus grande caldeira volcanique intacte du monde, grouillante de faune toute l'année.",
    dKilimanjaroName: 'Mont Kilimandjaro',
    dKilimanjaroTagline: "Toit de l'Afrique",
    dKilimanjaroDesc: "Relevez le défi d'un trek guidé vers le plus haut sommet d'Afrique, avec une cuisine de montagne Halal.",
    dTarangireName: 'Parc National de Tarangire',
    dTarangireTagline: 'Terre des Géants',
    dTarangireDesc: "Célèbre pour ses immenses troupeaux d'éléphants et ses baobabs anciens. Un safari paisible et moins fréquenté.",
    dManyaraName: 'Lac Manyara',
    dManyaraTagline: 'Lions Grimpeurs et Flamants Roses',
    dManyaraDesc: "Une forêt d'eau souterraine spectaculaire, abritant des lions grimpeurs d'arbres et d'immenses colonies de flamants roses.",

    // Login / Register / Dashboard
    loginSubtitle: 'Yalamlam Travel & Tours',
    password: 'Mot de Passe',
    invalidCredentials: 'Email ou mot de passe invalide. Veuillez réessayer.',
    loggingIn: 'Connexion en cours...',
    noAccount: "Vous n'avez pas de compte?",
    signUpHere: 'Inscrivez-vous ici',
    staffHint: "Personnel: Utilisez votre email professionnel pour accéder au panneau d'administration",
    createAccount: 'Créer un Compte',
    joinYalamlam: 'Rejoignez Yalamlam Travel pour des offres exclusives',
    creatingAccount: 'Création du compte...',
    signUp: "S'inscrire",
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    logInHere: 'Connectez-vous ici',
    registerSuccess: '✅ Compte créé avec succès! Vous pouvez maintenant vous connecter.',
    welcomeBack: 'Bon retour,',
    myBookings: 'Mes Réservations',
    noBookingsYet: "Vous n'avez pas encore effectué de réservation.",
    browseTours: 'Parcourir les Circuits',
    refLabel: 'Réf:',
    datesLabel: 'Dates:',
    guestsLabel: 'Invités:',

    // Email OTP login & Forgot/Reset password
    loginWithPassword: 'Mot de Passe',
    loginWithEmailCode: 'Code par Email',
    sendCode: 'Envoyer le Code',
    sendingCode: 'Envoi en cours...',
    codeSentTo: 'Nous avons envoyé un code à 6 chiffres à',
    enterCode: 'Entrez le code à 6 chiffres',
    verifyAndLogin: 'Vérifier et Se Connecter',
    verifyingCode: 'Vérification...',
    resendCode: 'Renvoyer le code',
    resendCodeIn: 'Renvoyer dans',
    invalidCode: 'Code invalide ou expiré. Veuillez réessayer.',
    didntGetCode: "Vous n'avez pas reçu le code ?",
    useDifferentEmail: 'Utiliser un autre email',
    forgotPassword: 'Mot de passe oublié ?',
    forgotPasswordTitle: 'Mot de Passe Oublié',
    forgotPasswordSubtitle: 'Entrez votre email et nous vous enverrons un lien de réinitialisation',
    sendResetLink: 'Envoyer le Lien',
    sendingResetLink: 'Envoi en cours...',
    resetLinkSentTitle: 'Vérifiez Votre Email',
    resetLinkSentMessage: "Si un compte existe pour cet email, nous avons envoyé un lien de réinitialisation. Cela peut prendre une minute pour arriver.",
    backToLogin: 'Retour à la Connexion',
    resetPasswordTitle: 'Réinitialiser Votre Mot de Passe',
    resetPasswordSubtitle: 'Choisissez un nouveau mot de passe pour votre compte',
    newPassword: 'Nouveau Mot de Passe',
    confirmNewPassword: 'Confirmer le Nouveau Mot de Passe',
    resetPasswordButton: 'Réinitialiser le Mot de Passe',
    resettingPassword: 'Réinitialisation...',
    passwordsDontMatch: 'Les mots de passe ne correspondent pas.',
    passwordTooShort: 'Le mot de passe doit contenir au moins 6 caractères.',
    resetPasswordSuccess: '✅ Mot de passe mis à jour avec succès ! Redirection vers la connexion...',
    invalidResetLink: 'Ce lien de réinitialisation est invalide ou a expiré.',
    requestNewResetLink: 'Demander un nouveau lien',
    changePasswordTitle: 'Changer le Mot de Passe',
    changePasswordSubtitle: 'Mettez à jour le mot de passe de votre compte',
    currentPassword: 'Mot de Passe Actuel',
    changePasswordButton: 'Changer le Mot de Passe',
    changingPassword: 'Mise à jour...',
    passwordChangedSuccess: '✅ Mot de passe changé avec succès.',
    incorrectCurrentPassword: 'Le mot de passe actuel est incorrect.',
  },

  tr: {
    // Navigation
    home: 'Ana Sayfa',
    tours: 'Turlar',
    halalTourism: 'Helal Turizm',
    destinations: 'Destinasyonlar',
    contact: 'İletişim',
    login: 'Giriş Yap',
    register: 'Kaydol',
    bookNow: 'Rezervasyon',
    myDashboard: 'Panelim',
    logout: 'Çıkış',
    
    // Home Page
    heroTitle: 'Vahşi Doğayı Keşfet,',
    heroSubtitle: 'İmanınızdan Ödün Vermeden',
    heroDescription: 'Garantili helal yemekler, özel namaz alanları ve mütevazı programlarla premium Afrika safari turları.',
    certified: '100% MÜSLÜMAN DOSTU & HELAL SERTİFİKALI',
    exploreTours: 'Turları Keşfet',
    whyChooseUs: 'Neden Yalamlam?',
    
    // Common
    price: 'Fiyat',
    duration: 'Süre',
    days: 'Gün',
    learnMore: 'Daha Fazla',
    viewDetails: 'Detayları Gör',
    startingFrom: 'Başlangıç',
    perPerson: 'kişi başı',
    bookThisTour: 'Bu Turu Rezervasyon Yap',
    noPaymentRequired: 'Bugün ödeme gerekmez. Uygunluk için sizi arayacağız.',
    needHelp: 'Yardıma mı ihtiyacınız var? WhatsApp',
    freeCancellation: '48 saat öncesine kadar ücretsiz iptal',
    
    // Tour Details
    aboutTour: 'Bu Tur Hakkında',
    itinerary: 'Günlük Program',
    included: 'Dahil Olanlar',
    excluded: 'Dahil Olmayanlar',
    halalCertified: '100% Helal Sertifikalı',
    customerReviews: 'Müşteri Yorumları',
    writeReview: 'Yorum Yaz',
    shareExperience: 'Deneyiminizi Paylaşın',
    yourName: 'Adınız',
    rating: 'Değerlendirme',
    excellent: 'Mükemmel',
    good: 'İyi',
    average: 'Ortalama',
    poor: 'Zayıf',
    terrible: 'Çok Kötü',
    tellUsAboutTrip: 'Seyahatiniz hakkında bize anlatın...',
    submitReview: 'Yorum Gönder',
    noReviewsYet: 'Henüz yorum yok. İlk siz olun!',
    reviewPending: 'Cezakallahu Hayran! Yorumunuz onay bekliyor.',
    
    // Booking
    bookingForm: 'Rezervasyon Formu',
    firstName: 'Ad',
    lastName: 'Soyad',
    email: 'E-posta',
    phone: 'Telefon',
    startDate: 'Başlangıç Tarihi',
    endDate: 'Bitiş Tarihi',
    numberOfGuests: 'Misafir Sayısı',
    specialRequests: 'Özel İstekler',
    submitBooking: 'Rezervasyon Gönder',
    bookingSuccess: 'Rezervasyon alındı! 24 saat içinde size ulaşacağız.',
    
    // Contact
    contactUs: 'Bize Ulaşın',
    contactDescription: 'Sorularınız mı var? Mükemmel helal safari planlamanız için burayız.',
    name: 'İsim',
    message: 'Mesaj',
    sendMessage: 'Gönder',
    messageSuccess: 'Mesaj gönderildi! Yakında dönüş yapacağız.',
    
    // Footer
    quickLinks: 'Hızlı Bağlantılar',
    legalPolicies: 'Yasal & Politikalar',
    termsConditions: 'Şartlar ve Koşullar',
    privacyPolicy: 'Gizlilik Politikası',
    cancellationPolicy: 'İptal Politikası',
    contactInfo: 'İletişim',
    reservations: 'Rezervasyonlar',
    zanzibarOffice: 'Zanzibar Ofisi',
    customerSupport: 'Müşteri Desteği',
    allRightsReserved: 'Tüm Hakları Saklıdır',
    
    // Filters
    searchTours: 'Tur veya destinasyon ara...',
    allCategories: 'Tüm Kategoriler',
    anyPrice: 'Her Fiyat',
    under500: '500$ Altı',
    under1000: '1,000$ Altı',
    under2000: '2,000$ Altı',
    under5000: '5,000$ Altı',
    sortBy: 'Sırala',
    newestFirst: 'En Yeni',
    priceLowHigh: 'Fiyat: Düşükten Yükseğe',
    priceHighLow: 'Fiyat: Yüksekten Düşüğe',
    durationShort: 'Süre: En Kısa',
    showingTours: 'Gösteriliyor',
    toursPlural: 'tur',
    tour: 'tur',
    noToursFound: 'Tur bulunamadı',
    tryAdjustingFilters: 'Filtrelerinizi ayarlamayı deneyin.',
    clearAllFilters: 'Filtreleri Temizle',
    
    // Categories
    zanzibarTours: 'Zanzibar Turları',
    tanzaniaSafaris: 'Tanzanya Safarileri',
    halalPackages: 'Helal Paketler',
    kilimanjaro: 'Kilimanjaro',

    // Navbar
    selectLanguage: 'DİL SEÇİN',

    // Home - Why Choose Us cards
    halalMealsTitle: '%100 Helal Yemekler',
    halalMealsDesc: 'Her yemek sıkı bir şekilde helal sertifikalıdır ve temiz, mütevazı ortamlarda hazırlanır.',
    prayerFacilitiesTitle: 'Namaz Alanları',
    prayerFacilitiesDesc: 'Programlar namaz vakitlerine göre planlanır ve temiz camilere erişim garanti edilir.',
    modestSafeTitle: 'Mütevazı ve Güvenli',
    modestSafeDesc: 'Özel transferler, mütevazılığa duyarlı rehberler ve aile dostu ortamlar.',

    // Tours page
    exploreToursTitle: 'Turlarımızı Keşfedin',
    exploreToursSubtitle: 'Özenle seçilmiş helal dostu safarilerimizi, Zanzibar plaj tatillerimizi ve Kilimanjaro maceralarımızı keşfedin.',
    loadingTours: 'Turlar yükleniyor...',

    // Tour Details page
    backToAllTours: '← Tüm Turlara Dön',
    loadingTourDetails: 'Tur detayları yükleniyor...',
    tourNotFound: 'Tur bulunamadı.',
    goBack: 'Geri dön',
    whatsIncluded: 'Dahil Olanlar',
    whatsExcluded: 'Dahil Olmayanlar',
    outOf5: '5 üzerinden',
    reviewsWord: 'yorum',
    cancel: 'İptal',
    submittingEllipsis: 'Gönderiliyor...',

    // Halal Tourism page
    yourFaithJourney: 'İmanınız, Yolculuğunuz',
    ultimateHalalExp: 'Eşsiz Helal Turizm Deneyimi',
    ultimateHalalExpDesc: "Tanzanya'nın vahşi güzelliğini ve Zanzibar cennetini İslami değerlerinizden asla ödün vermeden keşfedin. Detaylarla biz ilgileniriz; siz nimetlerin tadını çıkarın.",
    whyTravelWithUs: 'Neden Bizimle Seyahat Etmelisiniz?',
    whyTravelWithUsDesc: 'Standart bir tura sadece helal yemek eklemiyoruz. Tüm programı Müslüman gezgini düşünerek baştan inşa ediyoruz.',
    pillarDiningTitle: '%100 Helal Yemek',
    pillarDiningDesc: 'Yalnızca sertifikalı helal mutfaklarla çalışıyoruz. Gurme kamp yemeklerinden paketlenmiş safari öğle yemeklerine kadar, yemeğinizden asla şüphe duymayacaksınız. Minibarda alkol yok, çapraz bulaşma yok.',
    pillarPrayerTitle: 'Her Yerde Namaz Alanları',
    pillarPrayerDesc: 'Her araç temiz bir namaz seccadesi ve kıble pusulası ile donatılmıştır. Ortak lojmanlarımız özel namaz odaları sunar ve rehberlerimiz programı namaz vakitlerine göre ayarlamak üzere eğitilmiştir.',
    pillarTravelTitle: 'Özel ve Mütevazı Seyahat',
    pillarTravelDesc: 'Sadece aileniz ve rehberinizle kendi özel 4x4 safari aracınızda seyahat edin. Kalabalık, karma cinsiyetli grup turlarından kaçınarak mahremiyetinizi ve mütevazılığınızı her zaman koruruz.',
    pillarGuidesTitle: 'Kadın Rehberler ve Personel',
    pillarGuidesDesc: 'Hanımlarla mı seyahat ediyorsunuz? Kadın tur rehberleri, kadın şoförler ve sadece kadınlara özel spa ve gezi etkinlikleri düzenleyebiliriz.',
    pillarRamadanTitle: 'Ramazan ve Bayram Özel Programları',
    pillarRamadanDesc: 'Kutsal ayda mı seyahat ediyorsunuz? Özel sahur ve iftar programları, safari gezileri için paketlenmiş iftar kutuları ve özel bayram kutlama düzenlemeleri sunuyoruz.',
    pillarEthicalTitle: 'Etik ve Sorumlu',
    pillarEthicalDesc: 'İslam bize dünyanın koruyucuları olmayı öğretir. Safarilerimiz çevre dostudur, yerel vahşi yaşama saygı duyarız ve ziyaret ettiğimiz Tanzanya topluluklarına katkıda bulunuruz.',
    readyWorryFree: 'Endişesiz Bir Safariye Hazır mısınız?',
    readyWorryFreeDesc: 'Macera, dinlenme ve manevi ihtiyaçlarınızı mükemmel şekilde dengeleyen özel bir program hazırlayalım.',
    planMyHalalTrip: 'Helal Gezimi Planla',

    // Booking page
    planSafariTitle: 'Helal Safarinizi Planlayın',
    planSafariDesc: 'Aşağıya bilgilerinizi girin. Her şeyi inancınıza ve konforunuza göre özelleştireceğiz.',
    step: 'Adım',
    of: '/',
    complete: 'Tamamlandı',
    step1Title: '1. Seyahat Detayları',
    whereToGo: 'Nereye gitmek istiyorsunuz?',
    destZanzibar: 'Zanzibar (Plaj ve Stone Town)',
    destSerengeti: 'Serengeti ve Ngorongoro Safarisi',
    destKilimanjaro: 'Kilimanjaro Trekkingi',
    destCustom: 'Özel Çoklu Destinasyon',
    step2Title: '2. İman ve Konfor Tercihleri',
    step2Subtitle: 'Seyahatinizin değerlerinizle uyumlu olmasını sağlamak için geçerli olan her şeyi seçin.',
    halalMealsRequired: '%100 Helal Yemek Gerekli',
    prayerFacilitiesQibla: 'Odalarda Namaz Alanı ve Kıble Yönü',
    privateVehicleLabel: 'Özel 4x4 Araç (Sadece Aile)',
    femaleGuideLabel: 'Kadın Tur Rehberi (kadınlara özel veya mütevazılık tercihi için)',
    modestActivitiesLabel: 'Sadece Mütevazı Etkinlikler (Karma yüzme vb. yok)',
    step3Title: '3. Konaklama ve Etkinlikler',
    accommodationPref: 'Konaklama Tercihi',
    accLuxury: 'Lüks Safari Kampı / Tesisi',
    accVilla: 'Özel Aile Villası',
    accBudget: 'Ekonomik Kamp',
    accHalalHotel: 'Sertifikalı Helal Otel',
    activitiesInterest: 'İlgi Duyulan Etkinlikler (Birden fazla seçin)',
    actWildlifeSafari: 'Vahşi Yaşam Safarisi',
    actSnorkelling: 'Şnorkelle Dalış',
    actSpiceTour: 'Baharat Turu',
    actCulturalVillage: 'Kültürel Köy',
    actDolphinTour: 'Yunus Turu',
    actSunsetCruise: 'Gün Batımı Turu',
    step4Title: '4. İletişim Bilgileri',
    whatsappNumberLabel: 'WhatsApp Numarası (Ülke Kodu ile)',
    specialRequestsPlaceholder: 'örn: Ramazanda seyahat, camiye yakın oda ihtiyacı, balayı kutlaması...',
    back: 'Geri',
    nextStep: 'Sonraki Adım',
    savingRequest: 'Kaydediliyor...',
    emailAddress: 'E-posta Adresi',

    // Contact page
    getInTouch: 'Bizimle İletişime Geçin',
    getInTouchDesc: 'Helal turlarımız hakkında sorularınız mı var? Bir programı özelleştirmek mi istiyorsunuz? Mükemmel gezinizi planlamanıza yardımcı olmak için buradayız.',
    callWhatsappUs: 'Arayın veya WhatsApp Yazın',
    availableHours: 'Saat 8:00 - 20:00 EAT arası hizmetinizdeyiz',
    emailUsTitle: 'Bize E-posta Gönderin',
    replyWithin24: '24 saat içinde yanıtlıyoruz',
    visitOurOffice: 'Ofisimizi Ziyaret Edin',
    officeLocation: 'Stone Town, Zanzibar',
    officeCountry: 'Tanzanya, Doğu Afrika',
    sendUsMessageTitle: 'Bize Mesaj Gönderin',
    sendUsMessageDesc: 'Aşağıdaki formu doldurun, ekibimiz Inşallah kısa sürede size dönüş yapacaktır.',
    fullName: 'Ad Soyad',
    phoneNumber: 'Telefon Numarası',
    yourMessage: 'Mesajınız',
    sendingEllipsis: 'Gönderiliyor...',
    contactSuccessBanner: 'Cezakallahu Hayran! Mesajınız başarıyla gönderildi.',

    // Destinations page
    discoverTanzania: "Tanzanya'yı Keşfedin",
    discoverTanzaniaDesc: "Kilimanjaro'nun karlı zirvelerinden Hint Okyanusu'nun turkuaz sularına kadar.",
    toursAvailable: 'Tur Mevcut',
    viewToursLink: 'Turları Gör',
    dZanzibarName: 'Zanzibar Adası',
    dZanzibarTagline: 'Baharat Adası ve Plaj Cenneti',
    dZanzibarDesc: "Bembeyaz kumsallarda dinlenin, tarihi Stone Town'ı keşfedin ve dünya standartlarında helal deniz ürünlerinin tadını çıkarın.",
    dSerengetiName: 'Serengeti Milli Parkı',
    dSerengetiTagline: 'Büyük Göç',
    dSerengetiDesc: "Milyonlarca gnu ve Büyük Beşli'yi doğal, vahşi yaşam alanlarında izleyin.",
    dNgorongoroName: 'Ngorongoro Krateri',
    dNgorongoroTagline: 'Cennet Bahçesi',
    dNgorongoroDesc: 'Dünyanın en büyük sağlam volkanik kalderasına inin, yıl boyunca vahşi yaşamla dolu.',
    dKilimanjaroName: 'Kilimanjaro Dağı',
    dKilimanjaroTagline: "Afrika'nın Çatısı",
    dKilimanjaroDesc: "Helal dağ mutfağıyla Afrika'nın en yüksek zirvesine rehberli bir trekle kendinizi zorlayın.",
    dTarangireName: 'Tarangire Milli Parkı',
    dTarangireTagline: 'Devler Diyarı',
    dTarangireDesc: 'Devasa fil sürüleri ve antik baobab ağaçlarıyla ünlü. Huzurlu, daha az kalabalık bir safari.',
    dManyaraName: 'Manyara Gölü',
    dManyaraTagline: 'Ağaç Aslanları ve Flamingolar',
    dManyaraDesc: 'Ağaçlara tırmanan aslanlara ve devasa pembe flamingo sürülerine ev sahipliği yapan çarpıcı bir yeraltı suyu ormanı.',

    // Login / Register / Dashboard
    loginSubtitle: 'Yalamlam Travel & Tours',
    password: 'Şifre',
    invalidCredentials: 'Geçersiz e-posta veya şifre. Lütfen tekrar deneyin.',
    loggingIn: 'Giriş yapılıyor...',
    noAccount: 'Hesabınız yok mu?',
    signUpHere: 'Buradan kaydolun',
    staffHint: 'Personel: Yönetim paneline erişmek için şirket e-postanızı kullanın',
    createAccount: 'Hesap Oluştur',
    joinYalamlam: "Özel fırsatlar için Yalamlam Travel'a katılın",
    creatingAccount: 'Hesap oluşturuluyor...',
    signUp: 'Kaydol',
    alreadyHaveAccount: 'Zaten bir hesabınız var mı?',
    logInHere: 'Buradan giriş yapın',
    registerSuccess: '✅ Hesap başarıyla oluşturuldu! Şimdi giriş yapabilirsiniz.',
    welcomeBack: 'Tekrar hoş geldiniz,',
    myBookings: 'Rezervasyonlarım',
    noBookingsYet: 'Henüz bir rezervasyon yapmadınız.',
    browseTours: 'Turlara Göz Atın',
    refLabel: 'Ref:',
    datesLabel: 'Tarihler:',
    guestsLabel: 'Misafirler:',

    // Email OTP login & Forgot/Reset password
    loginWithPassword: 'Şifre',
    loginWithEmailCode: 'E-posta Kodu',
    sendCode: 'Kod Gönder',
    sendingCode: 'Gönderiliyor...',
    codeSentTo: '6 haneli bir kod şu adrese gönderildi:',
    enterCode: '6 haneli kodu girin',
    verifyAndLogin: 'Doğrula ve Giriş Yap',
    verifyingCode: 'Doğrulanıyor...',
    resendCode: 'Kodu tekrar gönder',
    resendCodeIn: 'Tekrar gönder:',
    invalidCode: 'Geçersiz veya süresi dolmuş kod. Lütfen tekrar deneyin.',
    didntGetCode: 'Kodu almadınız mı?',
    useDifferentEmail: 'Farklı bir e-posta kullan',
    forgotPassword: 'Şifrenizi mi unuttunuz?',
    forgotPasswordTitle: 'Şifremi Unuttum',
    forgotPasswordSubtitle: 'E-postanızı girin, size bir sıfırlama bağlantısı gönderelim',
    sendResetLink: 'Sıfırlama Bağlantısı Gönder',
    sendingResetLink: 'Gönderiliyor...',
    resetLinkSentTitle: 'E-postanızı Kontrol Edin',
    resetLinkSentMessage: 'Bu e-postaya ait bir hesap varsa, bir şifre sıfırlama bağlantısı gönderdik. Ulaşması bir dakika sürebilir.',
    backToLogin: 'Girişe Dön',
    resetPasswordTitle: 'Şifrenizi Sıfırlayın',
    resetPasswordSubtitle: 'Hesabınız için yeni bir şifre seçin',
    newPassword: 'Yeni Şifre',
    confirmNewPassword: 'Yeni Şifreyi Onayla',
    resetPasswordButton: 'Şifreyi Sıfırla',
    resettingPassword: 'Sıfırlanıyor...',
    passwordsDontMatch: 'Şifreler eşleşmiyor.',
    passwordTooShort: 'Şifre en az 6 karakter olmalıdır.',
    resetPasswordSuccess: '✅ Şifre başarıyla güncellendi! Girişe yönlendiriliyor...',
    invalidResetLink: 'Bu şifre sıfırlama bağlantısı geçersiz veya süresi dolmuş.',
    requestNewResetLink: 'Yeni bir bağlantı iste',
    changePasswordTitle: 'Şifreyi Değiştir',
    changePasswordSubtitle: 'Hesabınızın şifresini güncelleyin',
    currentPassword: 'Mevcut Şifre',
    changePasswordButton: 'Şifreyi Değiştir',
    changingPassword: 'Güncelleniyor...',
    passwordChangedSuccess: '✅ Şifre başarıyla değiştirildi.',
    incorrectCurrentPassword: 'Mevcut şifre yanlış.',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');
  const [isRTL, setIsRTL] = useState(false);

  useEffect(() => {
    // Check localStorage for saved language
    const savedLang = localStorage.getItem('yalamlam_lang') || 'en';
    setLang(savedLang);
    setIsRTL(savedLang === 'ar');
    
    // Set HTML direction
    document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = savedLang;
  }, []);

  const changeLanguage = (languageCode) => {
    setLang(languageCode);
    setIsRTL(languageCode === 'ar');
    localStorage.setItem('yalamlam_lang', languageCode);
    document.documentElement.dir = languageCode === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = languageCode;
  };

  const t = (key) => {
    return translations[lang][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, t, changeLanguage, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;